"""College applications: tracker, deadlines → To-Do, activities check, essay version history.

  college.py tracker                       rebuild College/Tracker.md from College/Schools/*.md (+ deadlines → To-Do)
  college.py activities                    check College/Activities.md against the Common App limits (writes a report)
  college.py words "<essay note>"          word count of the essay's ## Draft vs its limit
  college.py snapshot "<essay note>" [--why "what changed"]
                                           save the current ## Draft as a new version (if it changed)
  college.py history "<essay note>" [--diff N]
                                           versions + word counts + the latest change, for the tutor's context

Run with ~/miniconda3/envs/study/bin/python from ~/StudyVault. School notes keep their facts in frontmatter
(round, deadline, deadline_verified, platform, major, status, tier, deadlines: [{what, date}]) and a
"## ✅ Checklist" of `- [ ]` items; the tracker reads only those, so notes can hold anything else.
"""
import argparse
import difflib
import re
import sys
from datetime import date, datetime
from pathlib import Path

import yaml

VAULT = Path(__file__).resolve().parents[2]
COLLEGE = VAULT / "College"
SCHOOLS = COLLEGE / "Schools"
ESSAYS = COLLEGE / "Essays"
HISTORY = ESSAYS / "_history"
sys.path.insert(0, str(VAULT / "tools" / "sync"))

LIMITS = {"title": 50, "org": 100, "desc": 150}          # Common App "Activities and Experiences", 2026–27
OLD_CATEGORIES = {"work (paid)": "Employment or work (paid)", "junior rotc": "ROTC and Military"}


# ---------- reading notes ----------

def front(path):
    s = Path(path).read_text()
    m = re.match(r"---\n(.*?)\n---\n", s, re.S)
    return (yaml.safe_load(m.group(1)) or {}) if m else {}, s[m.end():] if m else s


def section(body, name):
    """Text under '## <name…>' up to the next '## '."""
    m = re.search(rf"^## [^\n]*{re.escape(name)}[^\n]*\n(.*?)(?=^## |\Z)", body, re.S | re.M)
    return m.group(1) if m else ""


def checklist(body):
    items = re.findall(r"^\s*- \[( |x|X)\] (.+)$", section(body, "Checklist"), re.M)
    return [(c.lower() == "x", t.strip()) for c, t in items]


def as_date(v):
    if isinstance(v, date):
        return v
    try:
        return date.fromisoformat(str(v)[:10])
    except (TypeError, ValueError):
        return None


def countdown(d, today):
    if not d:
        return "—"
    n = (d - today).days
    tag = "today" if n == 0 else ("past" if n < 0 else f"{n} d")
    return f"{d:%a %b %-d} ({tag})"


def essay_notes():
    out = []
    for f in sorted(ESSAYS.glob("*.md")):
        fm, body = front(f)
        if fm.get("type") == "essay":
            out.append((f, fm, body))
    return out


def words_of(text):
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"^>.*$", "", text, flags=re.M)          # callouts/comments aren't part of the essay
    return len(re.findall(r"[A-Za-z0-9À-ÿĞğİıŞşÇçÖöÜü'’-]+", text))


# ---------- tracker ----------

def tracker(push_todo=True):
    today = date.today()
    schools = []
    for f in sorted(SCHOOLS.glob("*.md")):
        fm, body = front(f)
        if fm.get("type") != "college":
            continue
        cl = checklist(body)
        done = sum(c for c, _ in cl)
        nxt = next((t for c, t in cl if not c), "")
        schools.append({"name": fm.get("school", f.stem), "file": f, "fm": fm, "done": done, "total": len(cl),
                        "next": nxt, "deadline": as_date(fm.get("deadline"))})
    essays = essay_notes()
    rank = {"ED": 0, "REA": 0, "EA": 0, "Rolling": 1, "RD": 2}
    schools.sort(key=lambda s: (s["deadline"] is None, s["deadline"] or date.max, rank.get(s["fm"].get("round"), 3)))

    out = ["# 🎓 College Tracker", "",
           f"> Generated by `tools/college/college.py tracker` on {datetime.now():%a %-m/%-d %-I:%M %p} from the notes "
           f"in [[College/Schools]] (edit those, not this). Deadlines also show in [[To-Do#🎓 College applications]].", ""]

    # upcoming dated items (next 21 days) across schools
    soon = []
    for s in schools:
        items = [{"what": f"{s['fm'].get('round', '')} application".strip(), "date": s["fm"].get("deadline")}] + \
                list(s["fm"].get("deadlines") or [])
        for d in items:
            dd = as_date(d.get("date"))
            if dd and 0 <= (dd - today).days <= 45 and s["fm"].get("status") not in ("submitted", "decision"):
                soon.append((dd, s["name"], d["what"]))
    out += ["## ⏰ Coming up", ""]
    out += [f"- **{countdown(d, today)}** · {n}: {w}" for d, n, w in sorted(soon)] or ["*Nothing dated in the next 45 days.*"]

    out += ["", "## 🏫 Schools", "",
            "| School | Round | Deadline | Platform | Essays | Checklist | Next step |", "|---|---|---|---|---|---|---|"]
    for s in schools:
        fm = s["fm"]
        mine = [e for e in essays if e[1].get("school") == s["name"]]
        drafted = sum(1 for e in mine if words_of(section(e[2], "Draft")) >= 30)
        ess = f"{drafted}/{len(mine)} drafted" if mine else "—"
        pct = f"{round(100 * s['done'] / s['total'])}% ({s['done']}/{s['total']})" if s["total"] else "—"
        dl = countdown(s["deadline"], today) + ("" if fm.get("deadline_verified") else " ⚠️ unverified")
        status = fm.get("status", "")
        name = f"[[{s['file'].relative_to(VAULT).with_suffix('')}|{s['name']}]]"
        if status in ("submitted", "decision"):
            name += f" ✅ {status}"
        out.append(f"| {name} | {fm.get('round', '?')} | {dl} | {fm.get('platform', '')} | {ess} | {pct} | {s['next'] or '—'} |")

    out += ["", "## ✍️ Essays", "", "| Essay | For | Words | Limit | Versions |", "|---|---|---|---|---|"]
    for f, fm, body in essays:
        n = words_of(section(body, "Draft"))
        lim = fm.get("limit")
        over = " ⚠️ over" if lim and n > int(lim) else ""
        nv = len(list((HISTORY / f.stem).glob("*.md"))) if (HISTORY / f.stem).exists() else 0
        out.append(f"| [[{f.relative_to(VAULT).with_suffix('')}|{f.stem}]] | {fm.get('school', '')} | {n}{over} | "
                   f"{lim or '—'} | {nv} |")
    missing_cds = [s["name"] for s in schools if "<!-- CDS:start -->" not in s["file"].read_text()]
    if missing_cds:
        out += ["", f"*No Common Data Set table yet for: {', '.join(missing_cds)}. Ask the tutor: `/college cds <school>`.*"]
    (COLLEGE / "Tracker.md").write_text("\n".join(out) + "\n")
    print(f"Tracker: {len(schools)} schools, {len(essays)} essays, {len(soon)} dated items in the next 45 days")

    if push_todo:
        push_deadlines(schools, today)


def push_deadlines(schools, today):
    """Each school's dated items → To-Do (course "College"). Submitted schools' items are ticked."""
    from todo import load, mark_done, render, upsert
    db = load()
    for s in schools:
        fm = s["fm"]
        items = [{"what": f"Submit {fm.get('round', '')} application".replace("  ", " "), "date": fm.get("deadline")}] + \
                list(fm.get("deadlines") or [])
        for d in items:
            dd = as_date(d.get("date"))
            if not dd:
                continue
            iid = f"college:{s['name']}:{re.sub(r'[^a-z0-9]+', '-', d['what'].lower()).strip('-')}"
            if fm.get("status") in ("submitted", "decision") or d.get("done"):
                mark_done(db, iid, "done (college tracker)")
                continue
            if dd < today and iid not in db["items"]:
                continue
            upsert(db, iid, course="College", title=f"{s['name']}: {d['what']}", due=dd.isoformat(), kind="task",
                   note=str(s["file"].relative_to(VAULT).with_suffix("")), source="college-tracker")
    render(db)


# ---------- activities ----------

def activities():
    f = COLLEGE / "Activities.md"
    s = f.read_text()
    entries = re.split(r"^### ", s.split("<!-- check:start -->")[0], flags=re.M)[1:]
    rows, notes = ["| # | Activity | Title | Org | Description | Flags |", "|---|---|---|---|---|---|"], []
    for e in entries:
        head = e.split("\n", 1)[0].strip()
        field = lambda k: (re.search(rf"^- \*\*{k}[^*]*:\*\*\s*(.*)$", e, re.M) or [None, ""])[1].strip()
        title, org, desc, cat = field("Title"), field("Organization"), field("Description"), field("Category")
        flags = []
        for k, v in (("title", title), ("org", org), ("desc", desc)):
            if len(v) > LIMITS[k]:
                flags.append(f"{k} over by {len(v) - LIMITS[k]}")
        if cat.lower() in OLD_CATEGORIES:
            flags.append(f'category renamed → "{OLD_CATEGORIES[cat.lower()]}"')
        if desc and not re.search(r"\d", desc):
            flags.append("no numbers (scale/impact?)")
        if re.search(r"\b(I|my|me)\b", desc):
            flags.append("first person (most drop 'I')")
        rows.append(f"| {head.split('.')[0]} | {head.split('.', 1)[-1].strip()[:40]} | {len(title)}/50 | {len(org)}/100 | "
                    f"{len(desc)}/150 | {'; '.join(flags) or '✓'} |")
    if len(entries) > 10:
        notes.append(f"⚠️ {len(entries)} entries: the Common App takes 10.")
    block = ("<!-- check:start -->\n## 🔎 Check (auto, " + date.today().isoformat() + ")\n\n" + "\n".join(rows) +
             ("\n\n" + "\n".join(notes) if notes else "") +
             "\n\n*Limits: optional title 50 · organization 100 · description 150 characters (spaces count). "
             "Pick each category in the portal: the 2026–27 list was reworded (e.g. \"Employment or work (paid)\").*\n"
             "<!-- check:end -->")
    if "<!-- check:start -->" in s:
        s = re.sub(r"<!-- check:start -->.*?<!-- check:end -->", lambda m: block, s, flags=re.S)
    else:
        s = s.rstrip() + "\n\n" + block + "\n"
    f.write_text(s)
    print("\n".join(rows + notes))


# ---------- essays: version history (context for the tutor) ----------

def essay_path(arg):
    p = Path(arg)
    if not p.suffix:
        p = p.with_suffix(".md")
    for cand in (p, VAULT / p, ESSAYS / p.name):
        if cand.exists():
            return cand
    sys.exit(f"essay note not found: {arg}")


def draft_of(path):
    _, body = front(path)
    return section(body, "Draft").strip()


def versions(path):
    d = HISTORY / path.stem
    return sorted(d.glob("*.md")) if d.exists() else []


def snapshot(arg, why=""):
    path = essay_path(arg)
    text = draft_of(path)
    vs = versions(path)
    if vs and vs[-1].read_text().split("\n---\n", 1)[-1].strip() == text:
        print(f"no change since {vs[-1].stem} ({words_of(text)} words)")
        return
    d = HISTORY / path.stem
    d.mkdir(parents=True, exist_ok=True)
    v = d / f"v{len(vs) + 1:02d} {datetime.now():%Y-%m-%d %H%M}.md"
    v.write_text(f"words: {words_of(text)}\nwhy: {why}\n---\n{text}\n")
    print(f"saved {v.relative_to(VAULT)} ({words_of(text)} words)")


def history(arg, diff_n=1):
    path = essay_path(arg)
    fm, body = front(path)
    vs = versions(path)
    print(f"# {path.stem} · limit {fm.get('limit', '—')} · now {words_of(section(body, 'Draft'))} words · {len(vs)} saved version(s)")
    for v in vs:
        head = v.read_text().split("\n---\n", 1)[0]
        w = re.search(r"words: (\d+)", head)
        why = re.search(r"why: (.*)", head)
        print(f"- {v.stem}: {w.group(1) if w else '?'} words{' · ' + why.group(1) if why and why.group(1) else ''}")
    for a, b in list(zip(vs, vs[1:]))[-diff_n:]:
        old = a.read_text().split("\n---\n", 1)[-1]
        new = b.read_text().split("\n---\n", 1)[-1]
        print(f"\n## What changed {a.stem.split(' ')[0]} → {b.stem.split(' ')[0]}")
        sm = difflib.SequenceMatcher(None, old.split(), new.split())
        for op, i1, i2, j1, j2 in sm.get_opcodes():
            if op == "equal":
                continue
            o, n = " ".join(old.split()[i1:i2]), " ".join(new.split()[j1:j2])
            print({"replace": f"~ «{o[:200]}» → «{n[:200]}»", "delete": f"- «{o[:200]}»",
                   "insert": f"+ «{n[:200]}»"}[op])
    fb = section(body, "Feedback log").strip()
    if fb:
        print("\n## Feedback log (most recent last)\n" + "\n".join(fb.splitlines()[-25:]))


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("tracker"); s.add_argument("--no-todo", action="store_true")
    sub.add_parser("activities")
    s = sub.add_parser("words"); s.add_argument("essay")
    s = sub.add_parser("snapshot"); s.add_argument("essay"); s.add_argument("--why", default="")
    s = sub.add_parser("history"); s.add_argument("essay"); s.add_argument("--diff", type=int, default=1)
    a = ap.parse_args()
    if a.cmd == "tracker":
        tracker(push_todo=not a.no_todo)
    elif a.cmd == "activities":
        activities()
    elif a.cmd == "words":
        p = essay_path(a.essay)
        fm, body = front(p)
        print(f"{words_of(section(body, 'Draft'))} words (limit {fm.get('limit', '—')})")
    elif a.cmd == "snapshot":
        snapshot(a.essay, a.why)
    elif a.cmd == "history":
        history(a.essay, a.diff)


if __name__ == "__main__":
    main()
